-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.ChatStateUpdate exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| -}
people : SelectionSet decodesTo Api.Object.Person -> SelectionSet (List decodesTo) Api.Object.ChatStateUpdate
people object_ =
    Object.selectionForCompositeField "people" [] object_ (identity >> Decode.list)


{-| -}
newMessages : SelectionSet decodesTo Api.Object.Message -> SelectionSet (List decodesTo) Api.Object.ChatStateUpdate
newMessages object_ =
    Object.selectionForCompositeField "newMessages" [] object_ (identity >> Decode.list)
