-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Person exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| -}
id : SelectionSet Int Api.Object.Person
id =
    Object.selectionForField "Int" "id" [] Decode.int


{-| -}
name : SelectionSet String Api.Object.Person
name =
    Object.selectionForField "String" "name" [] Decode.string


{-| -}
avatarSeed : SelectionSet Int Api.Object.Person
avatarSeed =
    Object.selectionForField "Int" "avatarSeed" [] Decode.int
