-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.SignInResult exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| -}
chatState : SelectionSet decodesTo Api.Object.ChatStateUpdate -> SelectionSet decodesTo Api.Object.SignInResult
chatState object_ =
    Object.selectionForCompositeField "chatState" [] object_ identity


{-| -}
personId : SelectionSet Int Api.Object.SignInResult
personId =
    Object.selectionForField "Int" "personId" [] Decode.int


{-| -}
personName : SelectionSet String Api.Object.SignInResult
personName =
    Object.selectionForField "String" "personName" [] Decode.string
