version: '3.2'

services:
  db:
    image: postgres:9.6
    environment:
      - PGHOST=database
      - PGDATABASE=webchat_prod
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "127.0.0.1:8085:9085"
    links:
      - "db:database"
    depends_on:
      - db
    restart: always

volumes:
  pgdata: