version: '3.2'

services:
  db:
    image: postgres:10.0
    environment:
      - PGHOST=database
      - PGDATABASE=postgres
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8085:8085"
    links:
      - "db:database"
    depends_on:
      - db
    restart: always

volumes:
  pgdata: