-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.ScalarCodecs exposing (..)

import Api.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias Datetime =
    Api.Scalar.Datetime


type alias Upload =
    Api.Scalar.Upload


codecs : Api.Scalar.Codecs Datetime Upload
codecs =
    Api.Scalar.defineCodecs
        { codecDatetime = defaultCodecs.codecDatetime
        , codecUpload = defaultCodecs.codecUpload
        }
